### ISSUE TITLE
Enarx Master Plan

### ISSUE THREAD

**Issue by platten** [platten/enarx-test#16]
<a href="https://github.com/npmccallum"><img src="https://avatars.githubusercontent.com/u/288304?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [npmccallum](https://github.com/npmccallum)**
_Tue Nov 12 17:19:29 2019_

----

- Reusable Components
  - Persistent storage
    - [ ] Design and Implement Block Encryption
    - [ ] Design and Implement Block Authentication
    - [ ] Choose and Implement Filesystem
  - SEV Attestation
    - [ ] Port sev repo to use rust-vmm kvm repo
    - [ ] Port sevctl to the new sev API
    - [ ] Expand library for SEV-ES
    - [ ] Expand library for SEV-SNP
  - OpenSSL (replace mbedtls)
    - [ ] Solve ld load problem
    - [ ] Solve CPUID problem
    - [ ] Solve network IO problem
  - Enarx VMM (name: TBD)
    - KVM Library (ketuvim => rust-vmm)
      - [ ] Merge x86_64_types improvements to x86_64 repo
      - [ ] Extract ketuvim core structures to rust-vmm kvm repo using x86_64
      - [ ] Merge rust-vmm kvm-ioctl repo to kvm repo
      - [ ] Transfer sev repo ownership to rust-vmm
    - Enarx VMM (name: TBD)
      - [ ] Design Host/Guest communication channel for syscall proxy (virtio-syscall?)
      - [ ] Document VMM
      - [ ] Implement VMM
    - Enarx μKernel (name: TBD)
      - [x] Design μKernel
      - [ ] Document μKernel
      - [ ] Implement μKernel
    - Enarx WASM Runtime
      - Cranelift
        - [x] architectural control
      - Wasmtime
        - [ ] architectural control
        - [ ] implement modularization
        - [ ] migrate unneded functionality to unused modules
      - WASI
        - [ ] Failure stubs for unsupported APIs
        - [ ] Implement Arguments
        - [ ] Implement Clocks
        - [ ] Implement Secure Sockets
        - [ ] Implement Filesystem
- Enarx Host Agent
  - Protocol
    - [ ] Choose transport
    - [ ] Choose serialization
    - [ ] Design protocol
    - [ ] Design instance state format
    - [ ] library/daemon
    - [ ] CLI 
    - [ ] Openshift integration
    - [ ] other OS support?
- Enarx Tenant CLI
    - [ ] Validate input before sending it to host
- Enarx Keep Scheduler
    - [ ] Node architecture discovery
    - [ ] Security-level negotiation
    - [ ] Design Keep input and output format
- Architectures
  - SGX
    - [x] Validate an SGX remote attestation 
    - [x] Establish encrypted channel to an SGX enclave 
    - [ ] Embed Wasmtime in an SGX enclave
    - [ ] Deliver WASM code to an SGX enclave across an encrypted channel
    - [ ] Evaluate stripped-down graphene?
 
  - SEV # please double check if content below here is correct. SEV got lost temporarily
    - [ ] Implement SEV attestation in our VMM
    - [ ] Implement SEV-ES attestation in our VMM
    - [ ] Implement SEV-SNP attestation in our VMM
    - [ ] Implement SEV support in our μKernel
    - [ ] Implement SEV-ES support in our μKernel
    - [ ] Implement SEV-SNP support in our μKernel

  - PEF
    - [ ] investigate once available

  - Others
    - [ ] track, investigate

  - Standardization Work
    - Evolve the WASI standard to better support our use case
        - [ ] Networking/secure sockets APIs
        - [ ] Low-level cryptography APIs
        - [ ] Secure clocks APIs
        - [ ] Secure random numbers APIs

- Testing
- Documentation
- Community

- Uncategorized
    - Key management design 
        - control plane
        - data plane
    - Key sharing 
    - GPU support - per platform, as available
    - FPGA support - per platform, as available
    - crypto hardware accelerator support
    - dev. tool integration (WASM + WASI): Eclipse, Eclipse Che...
    - Example applications/use cases (Java secure key store)

**Comment by platten** [comment]
<a href="https://github.com/MikeCamel"><img src="https://avatars.githubusercontent.com/u/1144836?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MikeCamel](https://github.com/MikeCamel)**
_Wed Nov 13 10:00:30 2019_

----

Note - all items above should (at least eventually) be listed as specific github issues.
