### ISSUE TITLE
Measure and attest SGX contents

### ISSUE THREAD

**Issue by platten** [platten/enarx-test#34]
<a href="https://github.com/npmccallum"><img src="https://avatars.githubusercontent.com/u/288304?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [npmccallum](https://github.com/npmccallum)**
_Fri Jan  3 23:11:32 2020_

----

Depends on #82.

**Comment by platten** [comment]
<a href="https://github.com/lkatalin"><img src="https://avatars.githubusercontent.com/u/22075926?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lkatalin](https://github.com/lkatalin)**
_Wed Jul  8 21:35:51 2020_

----

SGX attestation-related tasks (related to #824 ):

These are tasks that can be done without the communication channels between enclave and client established yet.

### Enclave side (generating the attestation Report):
- [x] Receive and handle an attestation request from client in code layer
- [x] Detect whether payload is running in SGX or SEV #671 enarx/enarx-keepldr#90
- [x] Implement `getatt()` synthetic syscall enarx/enarx-keepldr#31
- [x] Generate a Report for the current enclave using EREPORT #727 
- [ ] Generate a Diffie-Hellman keys **
- [ ] Embed DH pub key in the Report **
- [x] Get Intel's QE working with the current driver #912 
- [x] Get the QE's target info and pass it to the enclave to create the Report #913 enarx/enarx-keepldr#92
- [x] Have the QE verify the Report #914 

### Enarx Client Agent side (verifying a Quote):
- [x] Create an attestation request (to be later sent to enclave side)
- [ ] Retrieve a PCK cert chain from Intel’s service #789 
- [ ] Check validity of the PCK cert chain 
- [ ] Verify a dummy Quote:
  - [ ] Parse the Quote: get measurement, PCK leaf cert, signatures, etc.
  - [ ] Verify PCK is correct via PCK cert chain
  - [ ] Verify AK is correct via PCK
  - [ ] Verify AK signature on measurement is correct
  - [ ] Verify measurement is expected
- [ ] Generate Diffie-Hellman keys **

** = Requires further discussion / RFC underway

Some of [this code](https://github.com/lkatalin/demo/tree/encrypted-connection/intel-sgx) can be used as reference from 2019's attestation demo.
